part of check_in_domain;

enum ProfileActivityTypeOption {gameMatches, classesLessons, experiences, misc}
enum ProfileActivityOption {league, teamsRuns, equipment, tournament, camp, coaching, teaching, training, events, informalGame, oneOnOne, toRent, none}


List<ActivityOption> getActivityOptions(BuildContext? context) {
  return [
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-986gkuy968f3'), activity: ProfileActivityOption.toRent, title: (context != null) ? AppLocalizations.of(context).activityTypeRent : null, description: (context != null) ? AppLocalizations.of(context).activityTypeRentDes : null, icon: (context != null) ? Icons.vpn_key_rounded : null, activityType: ProfileActivityTypeOption.misc),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-748ng849joi4'), activity: ProfileActivityOption.camp, title: (context != null) ? AppLocalizations.of(context).activityTypeCamp : null, description: (context != null) ? AppLocalizations.of(context).activityTypeCampDes : null, icon: (context != null) ? Icons.style : null, activityType: ProfileActivityTypeOption.experiences),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-1289fnm049j0'), activity: ProfileActivityOption.events, title: (context != null) ? AppLocalizations.of(context).activityTypeEvent : null, description: (context != null) ? AppLocalizations.of(context).activityTypeEvent : null, icon: (context != null) ? Icons.connect_without_contact_rounded : null, activityType: ProfileActivityTypeOption.experiences),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-098598gnei89'), activity: ProfileActivityOption.league, title: (context != null) ? AppLocalizations.of(context).activityTypeLeagues : null, description: (context != null) ? AppLocalizations.of(context).activityTypeLeaguesDes : null, icon: (context != null) ? Icons.star_rate_outlined : null, activityType: ProfileActivityTypeOption.experiences),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-6893hhi5940g'), activity: ProfileActivityOption.teaching, title: (context != null) ? AppLocalizations.of(context).activityTypeTeaching : null, description: (context != null) ? AppLocalizations.of(context).activityTypeTeachingDes : null, icon: (context != null) ? Icons.campaign_outlined : null, activityType: ProfileActivityTypeOption.classesLessons),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-692048fnji49'), activity: ProfileActivityOption.training, title: (context != null) ? AppLocalizations.of(context).activityTypeTrainingState : null, description: (context != null) ? AppLocalizations.of(context).activityTypeTrainingDes : null, icon: (context != null) ? Icons.timer : null, activityType: ProfileActivityTypeOption.classesLessons),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-692048fnji49'), activity: ProfileActivityOption.coaching, title: (context != null) ? AppLocalizations.of(context).activityTypeCoachingState : null, description: (context != null) ? AppLocalizations.of(context).activityTypeCoachingDes : null, icon: (context != null) ? Icons.sports : null, activityType: ProfileActivityTypeOption.classesLessons),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-6894j0293j09'), activity: ProfileActivityOption.informalGame, title: (context != null) ? AppLocalizations.of(context).activityTypeInformalGame : null, description: (context != null) ? AppLocalizations.of(context).activityTypeInformalGameDes : null, icon: (context != null) ? Icons.sports_tennis_outlined : null, activityType: ProfileActivityTypeOption.gameMatches),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-960jgg84995h'), activity: ProfileActivityOption.oneOnOne, title: (context != null) ? AppLocalizations.of(context).activityTypeOneOnOne : null, description: (context != null) ? AppLocalizations.of(context).activityTypeOneOnOneDes : null, icon: (context != null) ? Icons.sports_kabaddi_rounded : null, activityType: ProfileActivityTypeOption.gameMatches),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-82983oijg93n'), activity: ProfileActivityOption.teamsRuns, title: (context != null) ? AppLocalizations.of(context).activityTypeRuns : null, description: (context != null) ? AppLocalizations.of(context).activityTypeRunsDes : null, icon: (context != null) ? Icons.directions_run_rounded : null, activityType: ProfileActivityTypeOption.gameMatches),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-fhui9389h382'), activity: ProfileActivityOption.tournament, title: (context != null) ? AppLocalizations.of(context).activityTypeTournament : null, description: (context != null) ? AppLocalizations.of(context).activityTypeTournamentDes : null, icon: (context != null) ? Icons.sports_handball_rounded : null, activityType: ProfileActivityTypeOption.gameMatches),
    ActivityOption(activityId: UniqueId.fromUniqueString('6e24dae0-96dd-11eb-gfku-798gh9897h98'), activity: ProfileActivityOption.equipment, title: (context != null) ? AppLocalizations.of(context).activityTypeEquipment : null, description: (context != null) ? AppLocalizations.of(context).activityTypeEquipment : null, icon: (context != null) ? Icons.sports_basketball_outlined : null, activityType: ProfileActivityTypeOption.misc),
  ];
}
